enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - ia32
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.3.cjs
